apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mini-blockchain
  name: mini-blockchain
  namespace: mini-blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-blockchain
  template:
    metadata:
      labels:
        app: mini-blockchain
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - image: trendev/code-generator  
          imagePullPolicy: Always
          name: code-generator
          volumeMounts:
            - name: shared-data
              mountPath: "/tmp/secret-code"
          env:
            - name: CODE_SIZE
              value: "64"
            - name: DELAY
              value: "500"
          resources: {}
        - image: trendev/blockchain  
          imagePullPolicy: Always
          name: blockchain
          volumeMounts:
            - name: shared-data
              mountPath: "/tmp/secret-code"
          ports:
            - containerPort: 9000
          env:
            - name: N_SEED
              value: "5"
            - name: PORT
              value: "9000"
          resources: {}
       
