apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mini-blockchain
  name: mini-blockchain-pod
  namespace: mini-blockchain
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - image: trendev/code-generator
      imagePullPolicy: Always
      name: code-generator
      volumeMounts:
        - name: shared-data
          mountPath: "/tmp/secret-code"
      env:
        - name: CODE_SIZE
          value: "64"
        - name: DELAY
          value: "100"
      resources: {}
    - image: trendev/blockchain
      imagePullPolicy: Always
      name: blockchain
      volumeMounts:
        - name: shared-data
          mountPath: "/tmp/secret-code"
          readOnly: true
      ports:
        - containerPort: 9000
      env:
        - name: N_SEED
          value: "5"
        - name: PORT
          value: "9000"
      resources: {}
